/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class bying_imageprotect_base_JNIOpencv */

#ifndef _Included_bying_imageprotect_base_JNIOpencv
#define _Included_bying_imageprotect_base_JNIOpencv
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     bying_imageprotect_base_JNIOpencv
 * Method:    detectFace
 * Signature: (IILjava/lang/String;Ljava/lang/String;)[I
 */
JNIEXPORT jintArray JNICALL Java_bying_imageprotect_base_JNIOpencv_detectFace
  (JNIEnv *, jobject, jint, jint, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
